### PR TITLE
V3 Release Candidate

### LINKED ISSUE #112: Message Variables sent with the go-client does not support arbitrary JSON
To demonstrate I added a test to the end of messages_test here: https://github.com/kdparker/mailgun-go/blob/master/messages_test.go#L387

When you run this (with different orders of the actual tests) you get: 
```
--- FAIL: TestSendMGMessageVariables (0.00s)
       messages_test.go:414: expected these to be equal:
		ACTUAL:
		(string) (len=14) "{\"test\":\"123\"}"

		EXPECTED:
		(map[string]string) (len=1) {
		 (string) (len=4) "test": (string) (len=3) "123"
		}
```
```
--- FAIL: TestSendMGMessageVariables (0.00s)
       messages_test.go:414: expected these to be equal:
		ACTUAL:
		(string) (len=5) "false"

		EXPECTED:
		(bool) false
```
```
--- FAIL: TestSendMGMessageVariables (0.00s)
       messages_test.go:414: expected these to be equal:
		ACTUAL:
		(string) (len=14) "\"test-str-val\""

		EXPECTED:
		(string) (len=12) "test-str-val"
```

We noticed this error initially when noticing that when using this client, we were seeing this:
```
"user-variables": {
        "foo": "\"strval1\"",
        "is-test": "true",
        "bar": "\"strval2\"",
        "var": "\"strval3\""
    },
```
instead of my expected:
```
"user-variables": {
        "foo": "strval1",
        "is-test": true,
        "bar": "strval2",
        "var": "strval3"
    },
```

I can maybe help with the patch for this problem, but I first want to see if this behavior is intentional or not?

### LINKED ISSUE #113: Client periodically responds with vague EOF error
When I use the GetStatusFromErr() function to check for errors, I periodically get a -1 in return. The error returned by mailgun.Send() in these cases is the following.

```\"Post https://api.mailgun.net/v3/[mymailgundomain]/messages: EOF\"\n"```

This seems like it's the result of an uncaught io.EOF error somewhere. The mailgun-go package should check for that error and return a more helpful error message.

### LINKED ISSUE #138: Empty json response with empty credentials.
Hi everyone.

I think you have a litle issue when the Mailgun "object" is created with empty params.  Like this:
```
Mailer = mailgun.NewMailgun("", "", "")
```
The problem is that the response is an empty json object `{}`, so when the code of `Send` function arrives here:
```
var response sendMessageResponse
err = postResponseFromJSON(r, payload, &response)
if err == nil {
	mes = response.Message
	id = response.Id
}
```
It generates this error: `invalid character 'M' looking for beginning of value` It would be great to use something more verbose, something like: "Your credentials/domain are incorrect."

Thanks.

### LINKED ISSUE #142: Allow only CC or BCC recipients
Currently the validation in `messages.go` requires at least one recipient in the `to` field. However, I should be permitted to send an email as long as there is at least one recipient in the `to`, `cc`, OR `bcc` field.

### PR DESCRIPTION
**Pull request by thrawn01**
## Purpose
Mailgun is currently revamping our public API documentation. As apart of this effort I'm updating mailgun-go to fill in the gaps in API compatibility. Since the `mailgun.Mailgun` interface is changing again, I'm taking this opportunity to clean up method naming and introduce `context.Context` to the method calls. Also as a part of this revamp effort I'm updating the mailgun.com documentation with golang examples from this V3 pull request.

## List of added methods
* Added `AddDomainIP()`
* Added `ListDomainIPS()`
* Added `DeleteDomainIP()`
* Added `ListIPS()`
* Added `GetIP()`
* Added `GetDomainTracking()`
* Added `GetDomainConnection()`
* Added `UpdateDomainConnection()`
* Added `CreateExport()`
* Added `ListExports()`
* Added `GetExports()`
* Added `GetExportLink()`
* Added `CreateTemplate()`
* Added `GetTemplate()`
* Added `UpdateTemplate()`
* Added `DeleteTemplate()`
* Added `ListTemplates()`
* Added `AddTemplateVersion()`
* Added `GetTemplateVersion()`
* Added `UpdateTemplateVersion()`
* Added `DeleteTemplateVersion()`
* Added `ListTemplateVersions()`

## List of improvements
* Added a `mailgun.MockServer` which duplicates part of the mailgun API; suitable for testing
* `ListMailingLists()` now uses the `/pages` API and returns an iterator
* `ListMembers()` now uses the `/pages` API and returns an iterator
* Renamed public interface methods to be consistent. IE: `GetThing(), ListThing(), CreateThing()`
* Moved event objects into the `mailgun/events` package, so names like `MailingList` returned by API calls and `MailingList` as an event object don't conflict and confuse users.
* Now using context.Context for all network operations
* Test suite will run without MG_ env vars defined
* ListRoutes() now uses the iterator interface
* Added SkipNetworkTest()
* Removed ginkgo and gomega tests
* Removed GetStats() As the /stats endpoint is depreciated
* Renamed GetStatsTotals() to GetStats()
* Renamed GetUnsubscribes to ListUnsubscribes()
* Renamed Unsubscribe() to CreateUnsubscribe()
* Renamed RemoveUnsubscribe() to DeleteUnsubscribe()
* GetStats() now takes an `*opt` argument to pass optional parameters
* Modified GetUnsubscribe() to follow the API
* Now using golang modules
* Removed deprecated methods NewMessage and NewMIMEMessage
* ListCredentials() now returns an iterator
* ListUnsubscribes() now returns an paging iterator
* CreateDomain now accepts CreateDomainOption{}
* CreateDomain() now supports all optional parameters not just spam_action and wildcard.
* ListComplaints() now returns a page iterator
* Renamed `TagItem` to `Tag`
* ListBounces() now returns a page iterator
* API responses with CreatedAt fields are now unmarshalled into RFC2822
* Removed GetCode() from `Bounce` struct. Verified API returns 'string' and not 'int'
* DomainList() now returns an iterator
* Updated godoc documentation
* Removed more deprecated types
* Renamed ApiBase to APIBase
* Removed gobuffalo/envy dependency
* Updated copyright to 2019
* Removed mailgun cli from project
* Remove mention of the CLI in the README
* Fix #142 - Allow only CC or BCC recipients
* Fix #138 - Send() now warns if domain or api key is not provided
* Fix #113 - Send() now responds with a useful error if the server closed connection prematurely
* Fix #112 - Now unquote variables added to the message before send
* `ListEvents()` now returns a list of typed events
```go
mg := mailgun.NewMailgun(testDomain, testKey)

it := mg.ListEvents(&mailgun.EventsOptions{Limit: 100})

var page []mailgun.Event

// The entire operation should not take longer than 30 seconds
ctx, cancel := context.WithTimeout(context.Background(), time.Second*30)
defer cancel()

// For each page of 100 events
for it.Next(ctx, &page) {
	for _, e := range page {
		// You can access some fields via the interface
		fmt.Printf("Event: '%s' TimeStamp: '%s'\n", e.GetName(), e.GetTimestamp())

		// and you can act upon each event by type
		switch event := e.(type) {
		case *events.Accepted:
			fmt.Printf("Accepted: auth: %t\n", event.Flags.IsAuthenticated)
		case *events.Delivered:
			fmt.Printf("Delivered transport: %s\n", event.Envelope.Transport)
		case *events.Failed:
			fmt.Printf("Failed reason: %s\n", event.Reason)
		case *events.Clicked:
			fmt.Printf("Clicked GeoLocation: %s\n", event.GeoLocation.Country)
		case *events.Opened:
			fmt.Printf("Opened GeoLocation: %s\n", event.GeoLocation.Country)
		case *events.Rejected:
			fmt.Printf("Rejected reason: %s\n", event.Reject.Reason)
		case *events.Stored:
			fmt.Printf("Stored URL: %s\n", event.Storage.URL)
		case *events.Unsubscribed:
			fmt.Printf("Unsubscribed client OS: %s\n", event.ClientInfo.ClientOS)
		}
	}
}
```

## ToDo
* Change `CreatedAt` to RFC2822 when API changes are made

### CODE REVIEW

**Comment by thrawn01** [comment]
@mbanzon I made sure the README on this PR included ALL the changes I made because the diff is pretty huge. I did go a little crazy 💯 

Most of the brittle tests no longer hit the mailgun api, but instead hit a local mock I made of the mailgun API. This makes running the tests much more reliable. Eventually I would like to move all the tests to the mock API but that will have to be done later.

I'm currently waiting on a change from the /templates API developer to return RFC2822 dates. Once that has been deployed I'll merge this code if you approve. I then will deploy the documentation changes I made to the public mailgun documentation. I also wrote a blog post about the mailgun-go library which will be published this month.

**Comment by mbanzon** [comment]
@thrawn01 moving the CLI makes sense. Testing dependencies etc. could be limited to a minimum.

This is the output from `go mod download` which imho needs to be changed in order to make the library more _acceptable_ in a corporate code base:

```
➜  mailgun-go git:(pr/149) go mod download
go: finding github.com/pkg/errors v0.8.1
go: finding github.com/smartystreets/goconvey v0.0.0-20181108003508-044398e4856c
go: finding github.com/drhodes/golorem v0.0.0-20160418191928-ecccc744c2d9
go: finding github.com/gopherjs/gopherjs v0.0.0-20181103185306-d547d1d9531e
go: finding github.com/go-ini/ini v1.41.0
go: finding github.com/gobuffalo/envy v1.6.11
go: finding github.com/go-chi/chi v3.3.4+incompatible
go: finding github.com/jtolds/gls v4.2.1+incompatible
go: finding github.com/smartystreets/assertions v0.0.0-20180927180507-b2de0cb4f26d
go: finding gopkg.in/ini.v1 v1.41.0
go: finding github.com/thrawn01/args v0.3.0
go: finding github.com/fatih/structs v1.1.0
go: finding github.com/mailru/easyjson v0.0.0-20180823135443-60711f1a8329
go: finding github.com/mitchellh/mapstructure v1.1.2
go: finding github.com/joho/godotenv v1.3.0
go: finding github.com/spf13/pflag v1.0.3
go: finding github.com/kr/pty v1.1.3
go: finding github.com/rogpeppe/go-internal v1.0.0
go: finding github.com/spf13/cast v1.3.0
go: finding github.com/stretchr/testify v1.2.2
go: finding github.com/gobuffalo/packr/v2 v2.0.0-rc.11
go: finding github.com/markbates/deplist v1.0.5
go: finding github.com/pmezard/go-difflib v1.0.0
go: finding gopkg.in/errgo.v2 v2.1.0
go: finding github.com/gobuffalo/envy v1.6.10
go: finding github.com/gobuffalo/packd v0.0.0-20181207120301-c49825f8f6f4
go: finding github.com/sirupsen/logrus v1.2.0
go: finding github.com/markbates/oncer v0.0.0-20181203154359-bf2de49a0be2
go: finding github.com/gobuffalo/logger v0.0.0-20181127160119-5b956e21995c
go: finding github.com/markbates/safe v1.0.1
go: finding github.com/gobuffalo/genny v0.0.0-20181207164119-84844398a37d
go: finding golang.org/x/tools v0.0.0-20181206194817-bcd4e47d0288
go: finding github.com/karrick/godirwalk v1.7.7
go: finding github.com/spf13/cobra v0.0.3
go: finding github.com/markbates/oncer v0.0.0-20180924034138-723ad0170a46
go: finding github.com/gobuffalo/syncx v0.0.0-20181120194010-558ac7de985f
go: finding github.com/gobuffalo/envy v1.6.9
go: finding github.com/kr/pretty v0.1.0
go: finding github.com/gobuffalo/packr/v2 v2.0.0-rc.8
go: finding gopkg.in/check.v1 v1.0.0-20180628173108-788fd7840127
go: finding github.com/gobuffalo/packr/v2 v2.0.0-rc.10
go: finding golang.org/x/sys v0.0.0-20181206074257-70b957f3b65e
go: finding golang.org/x/net v0.0.0-20181207154023-610586996380
go: finding github.com/konsorten/go-windows-terminal-sequences v1.0.1
go: finding golang.org/x/sys v0.0.0-20180905080454-ebe1bf3edb33
go: finding github.com/stretchr/objx v0.1.1
go: finding golang.org/x/crypto v0.0.0-20180904163835-0709b304e793
go: finding golang.org/x/crypto v0.0.0-20181127143415-eb0de9b17e85
go: finding github.com/gobuffalo/plush v3.7.32+incompatible
go: finding golang.org/x/sync v0.0.0-20181108010431-42b317875d0f
go: finding github.com/gobuffalo/flect v0.0.0-20181114183036-47375f6d8328
go: finding github.com/kr/text v0.1.0
go: finding golang.org/x/crypto v0.0.0-20181203042331-505ab145d0a9
go: finding github.com/gobuffalo/genny v0.0.0-20181203201232-849d2c9534ea
go: finding github.com/markbates/oncer v0.0.0-20181014194634-05fccaae8fc4
go: finding github.com/gobuffalo/plushgen v0.0.0-20181203163832-9fc4964505c2
go: finding gopkg.in/yaml.v2 v2.2.2
go: finding golang.org/x/tools v0.0.0-20181205224935-3576414c54a4
go: finding github.com/gobuffalo/genny v0.0.0-20181119162812-e8ff4adce8bb
go: finding github.com/gobuffalo/packr v1.21.0
go: finding github.com/markbates/inflect v1.0.4
go: finding github.com/gobuffalo/plush v3.7.30+incompatible
go: finding github.com/gobuffalo/plush v3.7.22+incompatible
go: finding golang.org/x/tools v0.0.0-20181127232545-e782529d0ddd
go: finding github.com/karrick/godirwalk v1.7.5
go: finding github.com/gobuffalo/events v1.1.8
go: finding github.com/gobuffalo/plushgen v0.0.0-20181207152837-eedb135bd51b
go: finding golang.org/x/tools v0.0.0-20181127195227-b4e97c0ed882
go: finding github.com/gobuffalo/genny v0.0.0-20181206121324-d6fb8a0dbe36
go: finding github.com/kr/pty v1.1.1
go: finding github.com/gobuffalo/buffalo-plugins v1.8.2
go: finding github.com/gobuffalo/packd v0.0.0-20181124090624-311c6248e5fb
go: finding github.com/gobuffalo/logger v0.0.0-20181117211126-8e9b89b7c264
go: finding golang.org/x/tools v0.0.0-20181119130350-139d099f6620
go: finding github.com/gobuffalo/syncx v0.0.0-20181120191700-98333ab04150
go: finding github.com/gobuffalo/packd v0.0.0-20181114190715-f25c5d2471d7
go: finding github.com/gobuffalo/genny v0.0.0-20181128191930-77e34f71ba2a
go: finding github.com/gobuffalo/plushgen v0.0.0-20181128164830-d29dcb966cb2
go: finding github.com/inconshreveable/mousetrap v1.0.0
go: finding github.com/gobuffalo/plush v3.7.23+incompatible
go: finding github.com/gobuffalo/envy v1.6.7
go: finding github.com/gobuffalo/genny v0.0.0-20181127225641-2d959acc795b
go: finding github.com/gobuffalo/envy v1.6.5
go: finding github.com/gobuffalo/buffalo-plugins v1.6.11
go: finding golang.org/x/crypto v0.0.0-20181112202954-3d3f9f413869
go: finding github.com/gobuffalo/mapi v1.0.1
go: finding github.com/gobuffalo/genny v0.0.0-20181203165245-fda8bcce96b1
go: finding golang.org/x/net v0.0.0-20181114220301-adae6a3d119a
go: finding github.com/gobuffalo/release v1.1.1
go: finding github.com/spf13/viper v1.2.1
go: finding github.com/BurntSushi/toml v0.3.1
go: finding github.com/gobuffalo/release v1.0.72
go: finding github.com/markbates/going v1.0.2
go: finding golang.org/x/sys v0.0.0-20181107165924-66b7b1311ac8
go: finding github.com/gobuffalo/meta v0.0.0-20181127070345-0d7e59dd540b
go: finding github.com/gobuffalo/licenser v0.0.0-20181203160806-fe900bbede07
go: finding github.com/gobuffalo/events v1.1.7
go: finding github.com/gobuffalo/meta v0.0.0-20181114191255-b130ebedd2f7
go: finding github.com/gobuffalo/genny v0.0.0-20181114215459-0a4decd77f5d
go: finding github.com/gobuffalo/packr v1.20.0
go: finding github.com/gobuffalo/logger v0.0.0-20181109185836-3feeab578c17
go: finding golang.org/x/tools v0.0.0-20181114190951-94339b83286c
go: finding github.com/gobuffalo/envy v1.6.8
go: finding github.com/gobuffalo/packd v0.0.0-20181111195323-b2e760a5f0ff
go: finding github.com/gobuffalo/buffalo-plugins v1.6.9
go: finding github.com/gobuffalo/licenser v0.0.0-20181109171355-91a2a7aac9a7
go: finding github.com/gobuffalo/uuid v2.0.5+incompatible
go: finding github.com/gobuffalo/tags v2.0.11+incompatible
go: finding golang.org/x/crypto v0.0.0-20181106171534-e4dc69e5b2fd
go: finding github.com/Masterminds/semver v1.4.2
go: finding github.com/spf13/jwalterweatherman v1.0.0
go: finding github.com/hashicorp/hcl v1.0.0
go: finding github.com/gobuffalo/shoulders v1.0.1
go: finding github.com/onsi/gomega v1.4.1
go: finding github.com/gobuffalo/packr v1.19.0
go: finding github.com/spf13/pflag v1.0.2
go: finding github.com/gobuffalo/meta v0.0.0-20181025145500-3a985a084b0a
go: finding github.com/spf13/cast v1.2.0
go: finding github.com/gobuffalo/tags v2.0.14+incompatible
go: finding github.com/gobuffalo/licenser v0.0.0-20181027200154-58051a75da95
go: finding github.com/gobuffalo/genny v0.0.0-20181107223128-f18346459dbe
go: finding golang.org/x/sys v0.0.0-20180816055513-1c9583448a9c
go: finding github.com/serenize/snaker v0.0.0-20171204205717-a683aaf2d516
go: finding github.com/gobuffalo/logger v0.0.0-20181027193913-9cf4dd0efe46
go: finding github.com/gobuffalo/plush v3.7.21+incompatible
go: finding github.com/pelletier/go-toml v1.2.0
go: finding golang.org/x/sys v0.0.0-20181026203630-95b1ffbd15a5
go: finding golang.org/x/crypto v0.0.0-20181025213731-e84da0312774
go: finding github.com/gobuffalo/genny v0.0.0-20181106193839-7dcb0924caf1
go: finding github.com/magiconair/properties v1.8.0
go: finding github.com/gobuffalo/release v1.0.61
go: finding golang.org/x/sys v0.0.0-20180906133057-8cf3aee42992
go: finding github.com/gobuffalo/buffalo-plugins v1.6.7
go: finding golang.org/x/net v0.0.0-20181102091132-c10e9556a7bc
go: finding github.com/spf13/afero v1.1.2
go: finding github.com/sirupsen/logrus v1.1.1
go: finding golang.org/x/sys v0.0.0-20181106135930-3a76605856fd
go: finding golang.org/x/net v0.0.0-20181106065722-10aee1819953
go: finding github.com/gobuffalo/packd v0.0.0-20181031195726-c82734870264
go: finding github.com/gobuffalo/flect v0.0.0-20181104133451-1f6e9779237a
go: finding github.com/gobuffalo/github_flavored_markdown v1.0.7
go: finding github.com/gobuffalo/envy v1.6.6
go: finding github.com/gobuffalo/packr v1.15.1
go: finding golang.org/x/net v0.0.0-20180816102801-aaf60122140d
go: finding github.com/gobuffalo/validate v2.0.3+incompatible
go: finding golang.org/x/tools v0.0.0-20181105230042-78dc5bac0cac
go: finding github.com/gofrs/uuid v3.1.0+incompatible
go: finding github.com/gobuffalo/genny v0.0.0-20181027195209-3887b7171c4f
go: finding github.com/gobuffalo/events v1.1.5
go: finding github.com/gobuffalo/packr v1.15.0
go: finding github.com/gobuffalo/packd v0.0.0-20181027194105-7ae579e6d213
go: finding golang.org/x/tools v0.0.0-20181026183834-f60e5f99f081
go: finding github.com/gobuffalo/release v1.0.54
go: finding github.com/davecgh/go-spew v1.1.0
go: finding github.com/gobuffalo/flect v0.0.0-20181024204909-8f6be1a8c6c2
go: finding github.com/gobuffalo/licenser v0.0.0-20181025145548-437d89de4f75
go: finding github.com/mitchellh/mapstructure v1.0.0
go: finding github.com/gobuffalo/genny v0.0.0-20181027191429-94d6cfb5c7fc
go: finding github.com/gobuffalo/packd v0.0.0-20181104210303-d376b15f8e96
go: finding github.com/gobuffalo/packr v1.13.7
go: finding github.com/gobuffalo/genny v0.0.0-20181024195656-51392254bf53
go: finding github.com/markbates/inflect v1.0.3
go: finding github.com/sourcegraph/syntaxhighlight v0.0.0-20170531221838-bd320f5d308e
go: finding github.com/konsorten/go-windows-terminal-sequences v0.0.0-20180402223658-b729f2633dfe
go: finding github.com/gobuffalo/buffalo-plugins v1.6.5
go: finding github.com/gobuffalo/logger v0.0.0-20181027144941-73d08d2bb969
go: finding golang.org/x/tools v0.0.0-20181107215632-34b416bd17b3
go: finding golang.org/x/tools v0.0.0-20181024171208-a2dc47679d30
go: finding github.com/gobuffalo/logger v0.0.0-20181022175615-46cfb361fc27
go: finding golang.org/x/sys v0.0.0-20181025063200-d989b31c8746
go: finding golang.org/x/net v0.0.0-20181023162649-9b4f9f5ad519
go: finding golang.org/x/sys v0.0.0-20181026064943-731415f00dce
go: finding github.com/gobuffalo/licenser v0.0.0-20181128165715-cc7305f8abed
go: finding github.com/sergi/go-diff v1.0.0
go: finding github.com/gobuffalo/flect v0.0.0-20181019110701-3d6f0b585514
go: finding github.com/gobuffalo/genny v0.0.0-20181025145300-af3f81d526b8
go: finding golang.org/x/crypto v0.0.0-20181024171144-74cb1d3d52f4
go: finding github.com/microcosm-cc/bluemonday v1.0.1
go: finding golang.org/x/crypto v0.0.0-20181015023909-0c41d7ab0a0e
go: finding golang.org/x/sys v0.0.0-20181024145615-5cd93ef61a7c
go: finding golang.org/x/sys v0.0.0-20181022134430-8a28ead16f52
go: finding github.com/golang/protobuf v1.1.0
go: finding github.com/markbates/deplist v1.0.4
go: finding github.com/sourcegraph/annotate v0.0.0-20160123013949-f4cad6c6324d
go: finding golang.org/x/crypto v0.0.0-20181025113841-85e1b3f9139a
go: finding github.com/gobuffalo/packd v0.0.0-20181027190505-aafc0d02c411
go: finding github.com/gobuffalo/github_flavored_markdown v1.0.5
go: finding github.com/gobuffalo/release v1.0.53
go: finding github.com/gobuffalo/events v1.1.4
go: finding github.com/gobuffalo/packd v0.0.0-20181027182251-01ad393492c8
go: finding golang.org/x/net v0.0.0-20180921000356-2f5d2388922f
go: finding github.com/shurcooL/highlight_diff v0.0.0-20170515013008-09bb4053de1b
go: finding github.com/shurcooL/sanitized_anchor_name v0.0.0-20170918181015-86672fcb3f95
go: finding github.com/shurcooL/go v0.0.0-20180423040247-9e1955d9fb6e
go: finding github.com/shurcooL/go-goon v0.0.0-20170922171312-37c2f522c041
go: finding github.com/shurcooL/highlight_go v0.0.0-20170515013102-78fb10f4a5f8
go: finding github.com/shurcooL/octicon v0.0.0-20180602230221-c42b0e3b24d9
go: finding github.com/gobuffalo/buffalo-plugins v1.6.4
go: finding github.com/gobuffalo/events v1.1.3
go: finding github.com/gobuffalo/release v1.0.52
go: finding github.com/gobuffalo/licenser v0.0.0-20180924033006-eae28e638a42
go: finding github.com/gobuffalo/meta v0.0.0-20181018192820-8c6cef77dab3
go: finding github.com/gobuffalo/flect v0.0.0-20181018182602-fd24a256709f
go: finding github.com/gobuffalo/plush v3.7.16+incompatible
go: finding github.com/gobuffalo/genny v0.0.0-20180924032338-7af3a40f2252
go: finding github.com/gobuffalo/uuid v2.0.3+incompatible
go: finding golang.org/x/tools v0.0.0-20180917221912-90fa682c2a6e
go: finding github.com/gobuffalo/flect v0.0.0-20180907193754-dc14d8acaf9f
go: finding github.com/gobuffalo/envy v1.6.4
go: finding github.com/sirupsen/logrus v1.0.6
go: finding github.com/gobuffalo/github_flavored_markdown v1.0.4
go: finding gopkg.in/airbrake/gobrake.v2 v2.0.9
go: finding gopkg.in/gemnasium/logrus-airbrake-hook.v2 v2.1.2
go: finding golang.org/x/crypto v0.0.0-20180910181607-0e37d006457b
go: finding github.com/fatih/structs v1.0.0
go: finding github.com/markbates/oncer v0.0.0-20180924031910-e862a676800b
go: finding golang.org/x/sys v0.0.0-20180921163948-d47a0f339242
go: finding github.com/markbates/safe v1.0.0
go: finding github.com/markbates/inflect v1.0.0
go: finding golang.org/x/sys v0.0.0-20181011152604-fa43e7bc11ba
go: finding github.com/gobuffalo/plush v3.7.20+incompatible
go: finding github.com/joho/godotenv v1.2.0
go: finding github.com/gobuffalo/buffalo-plugins v1.5.1
go: finding github.com/gobuffalo/genny v0.0.0-20181017160347-90a774534246
go: finding github.com/sirupsen/logrus v1.1.0
go: finding golang.org/x/sys v0.0.0-20181005133103-4497e2df6f9e
go: finding golang.org/x/tools v0.0.0-20181006002542-f60d9635b16a
go: finding github.com/markbates/inflect v1.0.1
go: finding github.com/gobuffalo/flect v0.0.0-20181002182613-4571df4b1daf
go: finding golang.org/x/crypto v0.0.0-20181001203147-e3636079e1a4
go: finding github.com/gobuffalo/release v1.0.42
go: finding github.com/gobuffalo/events v1.0.8
go: finding github.com/gobuffalo/meta v0.0.0-20181018155829-df62557efcd3
go: finding github.com/gobuffalo/flect v0.0.0-20181007231023-ae7ed6bfe683
go: finding github.com/gobuffalo/buffalo-plugins v1.4.3
go: finding github.com/gobuffalo/uuid v2.0.4+incompatible
go: finding github.com/gobuffalo/events v1.0.7
go: finding golang.org/x/net v0.0.0-20181017193950-04a2e542c03f
go: finding golang.org/x/tools v0.0.0-20181017214349-06f26fdaaa28
go: finding github.com/gobuffalo/buffalo v0.13.0
go: finding golang.org/x/crypto v0.0.0-20181009213950-7c1a557ab941
go: finding github.com/gobuffalo/buffalo-plugins v1.0.4
go: finding golang.org/x/tools v0.0.0-20181013182035-5e66757b835f
go: finding github.com/markbates/sigtx v1.0.0
go: finding github.com/gobuffalo/mw-tokenauth v0.0.0-20181001105134-8545f626c189
go: finding github.com/gobuffalo/x v0.0.0-20181007152206-913e47c59ca7
go: finding github.com/gobuffalo/mw-paramlogger v0.0.0-20181005191442-d6ee392ec72e
go: finding github.com/gobuffalo/pop v4.8.4+incompatible
go: finding github.com/gobuffalo/buffalo-pop v1.0.5
go: finding github.com/monoculum/formam v0.0.0-20180901015400-4e68be1d79ba
go: finding github.com/gobuffalo/httptest v1.0.2
go: finding github.com/dgrijalva/jwt-go v3.2.0+incompatible
go: finding gopkg.in/mail.v2 v2.0.0-20180731213649-a0242b2233b4
go: finding golang.org/x/net v0.0.0-20181011144130-49bb7cea24b1
go: finding github.com/gobuffalo/makr v1.1.5
go: finding github.com/gobuffalo/release v1.0.38
go: finding github.com/markbates/grift v1.0.4
go: finding github.com/gobuffalo/mw-forcessl v0.0.0-20180802152810-73921ae7a130
go: finding github.com/fatih/color v1.7.0
go: finding github.com/gobuffalo/events v1.0.3
go: finding github.com/markbates/refresh v1.4.10
go: finding github.com/gobuffalo/mw-basicauth v1.0.3
go: finding github.com/markbates/hmax v1.0.0
go: finding github.com/gobuffalo/mw-contenttype v0.0.0-20180802152300-74f5a47f4d56
go: finding github.com/gobuffalo/mw-i18n v0.0.0-20180802152014-e3060b7e13d6
go: finding github.com/gobuffalo/buffalo v0.12.8-0.20181004233540-fac9bb505aa8
go: finding github.com/dustin/go-humanize v1.0.0
go: finding github.com/gobuffalo/genny v0.0.0-20181007153042-b8de7d566757
go: finding github.com/gobuffalo/buffalo-plugins v1.0.2
go: finding github.com/gobuffalo/pop v4.8.3+incompatible
go: finding gopkg.in/gomail.v2 v2.0.0-20160411212932-81ebce5c23df
go: finding github.com/gobuffalo/genny v0.0.0-20181005145118-318a41a134cc
go: finding github.com/mitchellh/go-homedir v1.0.0
go: finding golang.org/x/tools v0.0.0-20181003024731-2f84ea8ef872
go: finding github.com/gorilla/sessions v1.1.3
go: finding github.com/gobuffalo/mapi v1.0.0
go: finding github.com/ajg/form v0.0.0-20160822230020-523a5da1a92f
go: finding github.com/mattn/go-isatty v0.0.4
go: finding github.com/gobuffalo/genny v0.0.0-20181012161047-33e5f43d83a6
go: finding github.com/unrolled/secure v0.0.0-20181005190816-ff9db2ff917f
go: finding golang.org/x/tools v0.0.0-20181008205924-a2b3f7f249e9
go: finding github.com/gobuffalo/genny v0.0.0-20181003150629-3786a0744c5d
go: finding github.com/mattn/go-colorable v0.0.9
go: finding github.com/gobuffalo/mw-csrf v0.0.0-20180802151833-446ff26e108b
go: finding github.com/gobuffalo/release v1.0.35
go: finding github.com/gorilla/securecookie v1.1.1
go: finding github.com/gobuffalo/pop v4.8.2+incompatible
go: finding github.com/gorilla/sessions v1.1.2
go: finding github.com/dustin/go-humanize v0.0.0-20180713052910-9f541cc9db5d
go: finding github.com/cockroachdb/apd v1.1.0
go: finding github.com/shopspring/decimal v0.0.0-20180709203117-cd690d0c9e24
go: finding github.com/codegangsta/negroni v1.0.0
go: finding github.com/markbates/willie v1.0.9
go: finding github.com/gobuffalo/fizz v1.0.12
go: finding github.com/unrolled/secure v0.0.0-20180918153822-f340ee86eb8b
go: finding gopkg.in/alexcesaro/quotedprintable.v3 v3.0.0-20150716171945-2caba252f4dc
go: finding github.com/jackc/fake v0.0.0-20150926172116-812a484cc733
go: finding github.com/jackc/pgx v3.2.0+incompatible
go: finding github.com/nicksnyder/go-i18n v1.10.0
go: finding github.com/gobuffalo/x v0.0.0-20181003152136-452098b06085
go: finding github.com/cockroachdb/cockroach-go v0.0.0-20181001143604-e0a95dfd547c
go: finding github.com/go-sql-driver/mysql v1.4.0
go: finding golang.org/x/net v0.0.0-20180926154720-4dfa2610cdf3
go: finding github.com/gorilla/pat v0.0.0-20180118222023-199c85a7f6d1
go: finding github.com/satori/go.uuid v1.2.0
go: finding github.com/kballard/go-shellquote v0.0.0-20180428030007-95032a82bc51
go: finding github.com/mattn/go-sqlite3 v1.9.0
go: finding google.golang.org/appengine v1.2.0
go: finding github.com/jmoiron/sqlx v0.0.0-20180614180643-0dae4fefe7c0
go: finding golang.org/x/sys v0.0.0-20180927150500-dad3d9fb7b6e
go: finding golang.org/x/net v0.0.0-20180724234803-3673e40ba225
```

**Comment by thrawn01** [comment]
By removing the CLI I have to go.sum file down to this
```

**Comment by thrawn01** [comment]
@mbanzon Looks like it only downloads the test packages if someone actually runs the test. But go.mod doesn't differentiate between test modules and library modules
https://github.com/golang/go/issues/26913#issuecomment-411976222

I like the smaller dep listing, that look ok to you?

**Comment by thrawn01** [comment]
Merging this, then merging in #96  and #148 and tagging as `v3.0.0-rc.1`. I'm going to update some local projects with the release candidate. If all goes well I'll make a release as `v3.0.0`

**Pull request merged**
