### PR TITLE
Offline testing

### PR DESCRIPTION
**Pull request by heltonmarx**
Included an offline test case, would be a good example.

### CODE REVIEW

**Comment by thrawn01** [comment]
@heltonmarx Awesome! 

I'm planning on using [gomega](https://onsi.github.io/gomega/)  in #76 along with [ginkgo](https://github.com/onsi/ginkgo) for integration testing. What do you think about using atleast the matchers?

The test would become.
```golang
func TestSendMGOffline(t *testing.T) {
    RegisterTestingT(t)

    const (
        exampleDomain       = "testDomain"
        exampleAPIKey       = "testAPIKey"
        examplePublicAPIKey = "testPublicAPIKey"
        toUser              = "test@test.com"
        exampleMessage      = "Queue. Thank you"
        exampleID           = "<20111114174239.25659.5817@samples.mailgun.org>"
    )

    srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, req *http.Request) {
        Expect(req.Method).To(Equal(http.MethodPost))
        Expect(fmt.Sprintf("/%s/messages", exampleDomain)).To(Equal(req.URL.Path))

        values, err := parseContentType(req)
        Expect(err).To(BeNil())

        Expect(values.Get("from")).To(Equal(fromUser))
        Expect(values.Get("subject")).To(Equal(exampleSubject))
        Expect(values.Get("text")).To(Equal(exampleText))
        Expect(values.Get("to")).To(Equal(toUser))
        rsp := fmt.Sprintf(`{"message":"%s", "id":"%s"}`, exampleMessage, exampleID)
        fmt.Fprint(w, rsp)
    }))
    defer srv.Close()

    mg := NewMailgun(exampleDomain, exampleAPIKey, examplePublicAPIKey)
    mg.SetAPIBase(srv.URL)

    m := NewMessage(fromUser, exampleSubject, exampleText, toUser)
    msg, id, err := mg.Send(m)
    Expect(err).To(BeNil())
    Expect(msg).To(Equal(exampleMessage))
    Expect(id).To(Equal(exampleID))
}
```

**Comment by heltonmarx** [comment]
To be honest, I'm a big fan of [ensure](https://github.com/facebookgo/ensure) from Facebook, but [gomega](https://onsi.github.io/gomega/) looks good too. Another question: Which vendor tool do you have in mind ? [govendor](https://github.com/kardianos/govendor) ?!

**Comment by thrawn01** [comment]
I'll admit the one downside to gomega is it's a bit verbose. I'd be interested in giving `ensure` a try!
Use `ensure` in this PR and I'll modify #76 to use it as well. Ginkgo provides `GinkgoT()` to get at the golang std test object.
```go
ensure.DeepEqual(GinkgoT(), "me, "me")
```
Isn't to bad, and I can probably cache the *t in the `BeforeEach()` which is actually kinda nice.

On the subject of vendoring I would really like to avoid it, as I've run into issue with some of my other libraries that tried to use vendoring. Hopefully in another 6 Months the new `gps` tool the golang guys are working will be done and we can use that if needed. [See Article Here](https://blog.gopheracademy.com/advent-2016/saga-go-dependency-management/)

**Comment by heltonmarx** [comment]
@thrawn01 `ensure` added for all test cases, check it out !

**Comment by thrawn01** [comment]
ZOMG! LUV IT

And I'm loving the string compare.
```/usr/local/go/bin/go test -v github.com/mailgun/mailgun-go -run ^TestThings$
ensure.go:65: things_test.go:13: expected these to be equal:
	ACTUAL:
	(string) (len=4) "this"
	
	EXPECTED:
	(string) (len=8) "and this"
exit status 1
FAIL	github.com/mailgun/mailgun-go	0.010s
```
Gomega's string compare is pretty bad =(

**Pull request merged**
