### PR TITLE
Remove unsubscribes with matching tag

### PR DESCRIPTION
**Pull request by TamalSaha**

### CODE REVIEW

**Comment by mbanzon** [comment]
Thank you for the PR.

Can you refer to the part of the documentation that describe this?

**Comment by TamalSaha** [comment]
Here is the doc: https://documentation.mailgun.com/api-suppressions.html#delete-a-single-unsubscribe

**Comment by mbanzon** [comment]
Got it! Thank you.

Somehow I missed the "a" in the code. Merging shortly.

**Comment by TamalSaha** [comment]
Thanks @mbanzon

**Pull request merged**
