### PR TITLE
Adding web_scheme as a primary domain attribute

### LINKED ISSUE #301: Add 'web_scheme' as a primary attribute to Domain
**Issue**

In `v4.8.2` the `web_scheme` domain attribute is only supported as a create domain operation's option. As per the documentation however it is a primary attribute of the Domain entity: https://documentation.mailgun.com/en/latest/api-domains.html#domains

Also the current implementation only supports `web_scheme` in case of a domain creation, but not for retrieval or update.

**Desired outcome**

Having `web_scheme` supported as a primary attribute of the Domain entity.

### PR DESCRIPTION
**Pull request by Szasza**
Closes #301.

Also removed some unneeded stdout printing from the tag tests.

### CODE REVIEW

**Comment by Szasza** [comment]
@thrawn01 @teros0 I would like to ask for a review on this one. Unfortunately it took some time to get to it, but here it is 😅

**Comment by Szasza** [comment]
@obukhov-sergey @horkhe @dcorn I am unsure who to ping, but I would like to as for a review on this PR, so I can start working on adding this feature to the Mailgun Terraform provider too if all is good.

Thank you :)

**Review by thrawn01 — APPROVED** [review]

**Comment by thrawn01** [comment]
Sorry it took a while to get to this, thank you so much for this PR! it looks good!

**Comment by Szasza** [comment]
@thrawn01 no problem at the slightest, thank you for the review!

**Pull request merged**
